=== api-evangelist/amazon-storage-gateway/json-schema/amazon-storage-gateway-create-storedi-scsi-volume-input-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-storage-gateway/refs/heads/main/json-schema/amazon-storage-gateway-create-storedi-scsi-volume-input-schema.json",
  "title": "CreateStorediSCSIVolumeInput",
  "description": "<p>A JSON object containing one or more of the following fields:</p> <ul> <li> <p> <a>CreateStorediSCSIVolumeInput$DiskId</a> </p> </li> <li> <p> <a>CreateStorediSCSIVolumeInput$NetworkInterfaceId</a> </p> </li> <li> <p> <a>CreateStorediSCSIVolumeInput$PreserveExistingData</a> </p> </li> <li> <p> <a>CreateStorediSCSIVolumeInput$SnapshotId</a> </p> </li> <li> <p> <a>CreateStorediSCSIVolumeInput$TargetName</a> </p> </li> </ul>",
  "type": "object",
  "properties": {
    "GatewayARN": {
      "$ref": "#/components/schemas/GatewayARN"
    },
    "DiskId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DiskId"
        },
        {
          "description": "The unique identifier for the gateway local disk that is configured as a stored volume. Use <a href=\"https://docs.aws.amazon.com/storagegateway/latest/userguide/API_ListLocalDisks.html\">ListLocalDisks</a> to list disk IDs for a gateway."
        }
      ]
    },
    "SnapshotId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SnapshotId"
        },
        {
          "description": "The snapshot ID (e.g., \"snap-1122aabb\") of the snapshot to restore as the new stored volume. Specify this field if you want to create the iSCSI storage volume from a snapshot; otherwise, do not include this field. To list snapshots for your account use <a href=\"https://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-DescribeSnapshots.html\">DescribeSnapshots</a> in the <i>Amazon Elastic Compute Cloud API Reference</i>."
        }
      ]
    },
    "PreserveExistingData": {
      "allOf": [
        {
          "$ref": "#/components/schemas/boolean"
        },
        {
          "description": "<p>Set to <code>true</code> if you want to preserve the data on the local disk. Otherwise, set to <code>false</code> to create an empty volume.</p> <p>Valid Values: <code>true</code> | <code>false</code> </p>"
        }
      ]
    },
    "TargetName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TargetName"
        },
        {
          "description": "<p>The name of the iSCSI target used by an initiator to connect to a volume and used as a suffix for the target ARN. For example, specifying <code>TargetName</code> as <i>myvolume</i> results in the target ARN of <code>arn:aws:storagegateway:us-east-2:111122223333:gateway/sgw-12A3456B/target/iqn.1997-05.com.amazon:myvolume</code>. The target name must be unique across all volumes on a gateway.</p> <p>If you don't specify a value, Storage Gateway uses the value that was previously used for this volume as the new target name.</p>"
        }
      ]
    },
    "NetworkInterfaceId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NetworkInterfaceId"
        },
        {
          "description": "<p>The network interface of the gateway on which to expose the iSCSI target. Only IPv4 addresses are accepted. Use <a>DescribeGatewayInformation</a> to get a list of the network interfaces available on a gateway.</p> <p>Valid Values: A valid IP address.</p>"
        }
      ]
    },
    "KMSEncrypted": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "<p>Set to <code>true</code> to use Amazon S3 server-side encryption with your own KMS key, or <code>false</code> to use a key managed by Amazon S3. Optional.</p> <p>Valid Values: <code>true</code> | <code>false</code> </p>"
        }
      ]
    },
    "KMSKey": {
      "allOf": [
        {
          "$ref": "#/components/schemas/KMSKey"
        },
        {
          "description": "The Amazon Resource Name (ARN) of a symmetric customer master key (CMK) used for Amazon S3 server-side encryption. Storage Gateway does not support asymmetric CMKs. This value can only be set when <code>KMSEncrypted</code> is <code>true</code>. Optional."
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Tags"
        },
        {
          "description": "<p>A list of up to 50 tags that can be assigned to a stored volume. Each tag is a key-value pair.</p> <note> <p>Valid characters for key and value are letters, spaces, and numbers representable in UTF-8 format, and the following special characters: + - = . _ : / @. The maximum length of a tag's key is 128 characters, and the maximum length for a tag's value is 256.</p> </note>"
        }
      ]
    }
  },
  "required": [
    "GatewayARN",
    "DiskId",
    "PreserveExistingData",
    "TargetName",
    "NetworkInterfaceId"
  ]
}

=== api-evangelist/amazon-storage-gateway/examples/amazon-storage-gateway-create-storedi-scsi-volume-input-example.json
{
  "GatewayARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "DiskId": "example-value",
  "SnapshotId": "example-value",
  "PreserveExistingData": "example-value",
  "TargetName": "MyResource",
  "NetworkInterfaceId": "example-value",
  "KMSEncrypted": "example-value",
  "KMSKey": "example-value",
  "Tags": "example-value"
}
