=== api-evangelist/amazon-storage-gateway/json-schema/amazon-storage-gateway-describe-cache-output-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-storage-gateway/refs/heads/main/json-schema/amazon-storage-gateway-describe-cache-output-schema.json",
  "title": "DescribeCacheOutput",
  "description": "DescribeCacheOutput schema from Amazon Storage Gateway API",
  "type": "object",
  "properties": {
    "GatewayARN": {
      "$ref": "#/components/schemas/GatewayARN"
    },
    "DiskIds": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DiskIds"
        },
        {
          "description": "An array of strings that identify disks that are to be configured as working storage. Each string has a minimum length of 1 and maximum length of 300. You can get the disk IDs from the <a>ListLocalDisks</a> API."
        }
      ]
    },
    "CacheAllocatedInBytes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/long"
        },
        {
          "description": "The amount of cache in bytes allocated to a gateway."
        }
      ]
    },
    "CacheUsedPercentage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/double"
        },
        {
          "description": "Percent use of the gateway's cache storage. This metric applies only to the gateway-cached volume setup. The sample is taken at the end of the reporting period."
        }
      ]
    },
    "CacheDirtyPercentage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/double"
        },
        {
          "description": "The file share's contribution to the overall percentage of the gateway's cache that has not been persisted to Amazon Web Services. The sample is taken at the end of the reporting period."
        }
      ]
    },
    "CacheHitPercentage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/double"
        },
        {
          "description": "Percent of application read operations from the file shares that are served from cache. The sample is taken at the end of the reporting period."
        }
      ]
    },
    "CacheMissPercentage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/double"
        },
        {
          "description": "Percent of application read operations from the file shares that are not served from cache. The sample is taken at the end of the reporting period."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-storage-gateway/examples/amazon-storage-gateway-describe-cache-output-example.json
{
  "GatewayARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "DiskIds": "example-value",
  "CacheAllocatedInBytes": "example-value",
  "CacheUsedPercentage": "example-value",
  "CacheDirtyPercentage": "example-value",
  "CacheHitPercentage": "example-value",
  "CacheMissPercentage": "example-value"
}
