=== api-evangelist/amazon-storage-gateway/json-schema/amazon-storage-gateway-smb-file-share-info-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-storage-gateway/refs/heads/main/json-schema/amazon-storage-gateway-smb-file-share-info-schema.json",
  "title": "SMBFileShareInfo",
  "description": "The Windows file permissions and ownership information assigned, by default, to native S3 objects when S3 File Gateway discovers them in S3 buckets. This operation is only supported for S3 File Gateways.",
  "type": "object",
  "properties": {
    "FileShareARN": {
      "$ref": "#/components/schemas/FileShareARN"
    },
    "FileShareId": {
      "$ref": "#/components/schemas/FileShareId"
    },
    "FileShareStatus": {
      "$ref": "#/components/schemas/FileShareStatus"
    },
    "GatewayARN": {
      "$ref": "#/components/schemas/GatewayARN"
    },
    "KMSEncrypted": {
      "allOf": [
        {
          "$ref": "#/components/schemas/boolean"
        },
        {
          "description": "<p>Set to <code>true</code> to use Amazon S3 server-side encryption with your own KMS key, or <code>false</code> to use a key managed by Amazon S3. Optional.</p> <p>Valid Values: <code>true</code> | <code>false</code> </p>"
        }
      ]
    },
    "KMSKey": {
      "$ref": "#/components/schemas/KMSKey"
    },
    "Path": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Path"
        },
        {
          "description": "The file share path used by the SMB client to identify the mount point."
        }
      ]
    },
    "Role": {
      "$ref": "#/components/schemas/Role"
    },
    "LocationARN": {
      "$ref": "#/components/schemas/LocationARN"
    },
    "DefaultStorageClass": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StorageClass"
        },
        {
          "description": "<p>The default storage class for objects put into an Amazon S3 bucket by the S3 File Gateway. The default value is <code>S3_STANDARD</code>. Optional.</p> <p>Valid Values: <code>S3_STANDARD</code> | <code>S3_INTELLIGENT_TIERING</code> | <code>S3_STANDARD_IA</code> | <code>S3_ONEZONE_IA</code> </p>"
        }
      ]
    },
    "ObjectACL": {
      "$ref": "#/components/schemas/ObjectACL"
    },
    "ReadOnly": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "<p>A value that sets the write status of a file share. Set this value to <code>true</code> to set the write status to read-only, otherwise set to <code>false</code>.</p> <p>Valid Values: <code>true</code> | <code>false</code> </p>"
        }
      ]
    },
    "GuessMIMETypeEnabled": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "<p>A value that enables guessing of the MIME type for uploaded objects based on file extensions. Set this value to <code>true</code> to enable MIME type guessing, otherwise set to <code>false</code>. The default value is <code>true</code>.</p> <p>Valid Values: <code>true</code> | <code>false</code> </p>"
        }
      ]
    },
    "RequesterPays": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "<p>A value that sets who pays the cost of the request and the cost associated with data download from the S3 bucket. If this value is set to <code>true</code>, the requester pays the costs; otherwise, the S3 bucket owner pays. However, the S3 bucket owner always pays the cost of storing data.</p> <note> <p> <code>RequesterPays</code> is a configuration for the S3 bucket that backs the file share, so make sure that the configuration on the file share is the same as the S3 bucket configuration.</p> </note> <p>Valid Values: <code>true</code> | <code>false</code> </p>"
        }
      ]
    },
    "SMBACLEnabled": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "<p>If this value is set to <code>true</code>, it indicates that access control list (ACL) is enabled on the SMB file share. If it is set to <code>false</code>, it indicates that file and directory permissions are mapped to the POSIX permission.</p> <p>For more information, see <a href=\"https://docs.aws.amazon.com/storagegateway/latest/userguide/smb-acl.html\">Using Microsoft Windows ACLs to control access to an SMB file share</a> in the <i>Storage Gateway User Guide</i>.</p>"
        }
      ]
    },
    "AccessBasedEnumeration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "Indicates whether <code>AccessBasedEnumeration</code> is enabled."
        }
      ]
    },
    "AdminUserList": {
      "allOf": [
        {
          "$ref": "#/components/schemas/UserList"
        },
        {
          "description": "A list of users or groups in the Active Directory that have administrator rights to the file share. A group must be prefixed with the @ character. Acceptable formats include: <code>DOMAIN\\User1</code>, <code>user1</code>, <code>@group1</code>, and <code>@DOMAIN\\group1</code>. Can only be set if Authentication is set to <code>ActiveDirectory</code>."
        }
      ]
    },
    "ValidUserList": {
      "allOf": [
        {
          "$ref": "#/components/schemas/UserList"
        },
        {
          "description": "A list of users or groups in the Active Directory that are allowed to access the file share. A group must be prefixed with the @ character. Acceptable formats include: <code>DOMAIN\\User1</code>, <code>user1</code>, <code>@group1</code>, and <code>@DOMAIN\\group1</code>. Can only be set if Authentication is set to <code>ActiveDirectory</code>."
        }
      ]
    },
    "InvalidUserList": {
      "allOf": [
        {
          "$ref": "#/components/schemas/UserList"
        },
        {
          "description": "A list of users or groups in the Active Directory that are not allowed to access the file share. A group must be prefixed with the @ character. Acceptable formats include: <code>DOMAIN\\User1</code>, <code>user1</code>, <code>@group1</code>, and <code>@DOMAIN\\group1</code>. Can only be set if Authentication is set to <code>ActiveDirectory</code>."
        }
      ]
    },
    "AuditDestinationARN": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AuditDestinationARN"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the storage used for audit logs."
        }
      ]
    },
    "Authentication": {
      "$ref": "#/components/schemas/Authentication"
    },
    "CaseSensitivity": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CaseSensitivity"
        },
        {
          "description": "The case of an object name in an Amazon S3 bucket. For <code>ClientSpecified</code>, the client determines the case sensitivity. For <code>CaseSensitive</code>, the gateway determines the case sensitivity. The default value is <code>ClientSpecified</code>."
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Tags"
        },
        {
          "description": "A list of up to 50 tags assigned to the SMB file share, sorted alphabetically by key name. Each tag is a key-value pair. For a gateway with more than 10 tags assigned, you can view all tags using the <code>ListTagsForResource</code> API operation."
        }
      ]
    },
    "FileShareName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/FileShareName"
        },
        {
          "description": "<p>The name of the file share. Optional.</p> <note> <p> <code>FileShareName</code> must be set if an S3 prefix name is set in <code>LocationARN</code>, or if an access point or access point alias is used.</p> </note>"
        }
      ]
    },
    "CacheAttributes": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CacheAttributes"
        },
        {
          "description": "Refresh cache information for the file share."
        }
      ]
    },
    "NotificationPolicy": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NotificationPolicy"
        },
        {
          "description": "<p>The notification policy of the file share. <code>SettlingTimeInSeconds</code> controls the number of seconds to wait after the last point in time a client wrote to a file before generating an <code>ObjectUploaded</code> notification. Because clients can make many small writes to files, it's best to set this parameter for as long as possible to avoid generating multiple notifications for the same file in a small time period.</p> <note> <p> <code>SettlingTimeInSeconds</code> has no effect on the timing of the object uploading to Amazon S3, only the timing of the notification.</p> </note> <p>The following example sets <code>NotificationPolicy</code> on with <code>SettlingTimeInSeconds</code> set to 60.</p> <p> <code>{\\\"Upload\\\": {\\\"SettlingTimeInSeconds\\\": 60}}</code> </p> <p>The following example sets <code>NotificationPolicy</code> off.</p> <p> <code>{}</code> </p>"
        }
      ]
    },
    "VPCEndpointDNSName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DNSHostName"
        },
        {
          "description": "<p>Specifies the DNS name for the VPC endpoint that the SMB file share uses to connect to Amazon S3.</p> <note> <p>This parameter is required for SMB file shares that connect to Amazon S3 through a VPC endpoint, a VPC access point, or an access point alias that points to a VPC access point.</p> </note>"
        }
      ]
    },
    "BucketRegion": {
      "allOf": [
        {
          "$ref": "#/components/schemas/RegionId"
        },
        {
          "description": "<p>Specifies the Region of the S3 bucket where the SMB file share stores files.</p> <note> <p>This parameter is required for SMB file shares that connect to Amazon S3 through a VPC endpoint, a VPC access point, or an access point alias that points to a VPC access point.</p> </note>"
        }
      ]
    },
    "OplocksEnabled": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "<p>Specifies whether opportunistic locking is enabled for the SMB file share.</p> <note> <p>Enabling opportunistic locking on case-sensitive shares is not recommended for workloads that involve access to files with the same name in different case.</p> </note> <p>Valid Values: <code>true</code> | <code>false</code> </p>"
        }
      ]
    }
  }
}

=== api-evangelist/amazon-storage-gateway/examples/amazon-storage-gateway-update-smb-file-share-input-example.json
{
  "FileShareARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "KMSEncrypted": "example-value",
  "KMSKey": "example-value",
  "DefaultStorageClass": "example-value",
  "ObjectACL": "example-value",
  "ReadOnly": "example-value",
  "GuessMIMETypeEnabled": "example-value",
  "RequesterPays": "example-value",
  "SMBACLEnabled": "example-value",
  "AccessBasedEnumeration": "example-value",
  "AdminUserList": "example-value",
  "ValidUserList": "example-value",
  "InvalidUserList": "example-value",
  "AuditDestinationARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "CaseSensitivity": "example-value",
  "FileShareName": "MyResource",
  "CacheAttributes": "example-value",
  "NotificationPolicy": "example-value",
  "OplocksEnabled": "example-value"
}

=== api-evangelist/amazon-storage-gateway/examples/amazon-storage-gateway-smb-file-share-info-example.json
{
  "FileShareARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "FileShareId": "example-value",
  "FileShareStatus": "Active",
  "GatewayARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "KMSEncrypted": "example-value",
  "KMSKey": "example-value",
  "Path": "example-value",
  "Role": "example-value",
  "LocationARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "DefaultStorageClass": "example-value",
  "ObjectACL": "example-value",
  "ReadOnly": "example-value",
  "GuessMIMETypeEnabled": "example-value",
  "RequesterPays": "example-value",
  "SMBACLEnabled": "example-value",
  "AccessBasedEnumeration": "example-value",
  "AdminUserList": "example-value",
  "ValidUserList": "example-value",
  "InvalidUserList": "example-value",
  "AuditDestinationARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "Authentication": "example-value",
  "CaseSensitivity": "example-value",
  "Tags": "example-value",
  "FileShareName": "MyResource",
  "CacheAttributes": "example-value",
  "NotificationPolicy": "example-value",
  "VPCEndpointDNSName": "MyResource",
  "BucketRegion": "example-value",
  "OplocksEnabled": "example-value"
}
