=== api-evangelist/amazon-storage-gateway/json-schema/amazon-storage-gateway-describe-gateway-information-output-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-storage-gateway/refs/heads/main/json-schema/amazon-storage-gateway-describe-gateway-information-output-schema.json",
  "title": "DescribeGatewayInformationOutput",
  "description": "A JSON object containing the following fields:",
  "type": "object",
  "properties": {
    "GatewayARN": {
      "$ref": "#/components/schemas/GatewayARN"
    },
    "GatewayId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GatewayId"
        },
        {
          "description": "The unique identifier assigned to your gateway during activation. This ID becomes part of the gateway Amazon Resource Name (ARN), which you use as input for other operations."
        }
      ]
    },
    "GatewayName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/string"
        },
        {
          "description": "The name you configured for your gateway."
        }
      ]
    },
    "GatewayTimezone": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GatewayTimezone"
        },
        {
          "description": "A value that indicates the time zone configured for the gateway."
        }
      ]
    },
    "GatewayState": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GatewayState"
        },
        {
          "description": "A value that indicates the operating state of the gateway."
        }
      ]
    },
    "GatewayNetworkInterfaces": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GatewayNetworkInterfaces"
        },
        {
          "description": "A <a>NetworkInterface</a> array that contains descriptions of the gateway network interfaces."
        }
      ]
    },
    "GatewayType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GatewayType"
        },
        {
          "description": "The type of the gateway."
        }
      ]
    },
    "NextUpdateAvailabilityDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NextUpdateAvailabilityDate"
        },
        {
          "description": "The date on which an update to the gateway is available. This date is in the time zone of the gateway. If the gateway is not available for an update this field is not returned in the response."
        }
      ]
    },
    "LastSoftwareUpdate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/LastSoftwareUpdate"
        },
        {
          "description": "The date on which the last software update was applied to the gateway. If the gateway has never been updated, this field does not return a value in the response. This only only exist and returns once it have been chosen and set by the SGW service, based on the OS version of the gateway VM"
        }
      ]
    },
    "Ec2InstanceId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Ec2InstanceId"
        },
        {
          "description": "The ID of the Amazon EC2 instance that was used to launch the gateway."
        }
      ]
    },
    "Ec2InstanceRegion": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Ec2InstanceRegion"
        },
        {
          "description": "The Amazon Web Services Region where the Amazon EC2 instance is located."
        }
      ]
    },
    "Tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Tags"
        },
        {
          "description": "A list of up to 50 tags assigned to the gateway, sorted alphabetically by key name. Each tag is a key-value pair. For a gateway with more than 10 tags assigned, you can view all tags using the <code>ListTagsForResource</code> API operation."
        }
      ]
    },
    "VPCEndpoint": {
      "allOf": [
        {
          "$ref": "#/components/schemas/string"
        },
        {
          "description": "The configuration settings for the virtual private cloud (VPC) endpoint for your gateway."
        }
      ]
    },
    "CloudWatchLogGroupARN": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CloudWatchLogGroupARN"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the Amazon CloudWatch log group that is used to monitor events in the gateway. This field only only exist and returns once it have been chosen and set by the SGW service, based on the OS version of the gateway VM"
        }
      ]
    },
    "HostEnvironment": {
      "allOf": [
        {
          "$ref": "#/components/schemas/HostEnvironment"
        },
        {
          "description": "The type of hardware or software platform on which the gateway is running."
        }
      ]
    },
    "EndpointType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/EndpointType"
        },
        {
          "description": "<p>The type of endpoint for your gateway.</p> <p>Valid Values: <code>STANDARD</code> | <code>FIPS</code> </p>"
        }
      ]
    },
    "SoftwareUpdatesEndDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SoftwareUpdatesEndDate"
        },
        {
          "description": "Date after which this gateway will not receive software updates for new features."
        }
      ]
    },
    "DeprecationDate": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DeprecationDate"
        },
        {
          "description": "Date after which this gateway will not receive software updates for new features and bug fixes."
        }
      ]
    },
    "GatewayCapacity": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GatewayCapacity"
        },
        {
          "description": "Specifies the size of the gateway's metadata cache."
        }
      ]
    },
    "SupportedGatewayCapacities": {
      "allOf": [
        {
          "$ref": "#/components/schemas/SupportedGatewayCapacities"
        },
        {
          "description": "A list of the metadata cache sizes that the gateway can support based on its current hardware specifications."
        }
      ]
    },
    "HostEnvironmentId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/HostEnvironmentId"
        },
        {
          "description": "A unique identifier for the specific instance of the host platform running the gateway. This value is only available for certain host environments, and its format depends on the host environment type."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-storage-gateway/examples/amazon-storage-gateway-describe-gateway-information-output-example.json
{
  "GatewayARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "GatewayId": "example-value",
  "GatewayName": "MyResource",
  "GatewayTimezone": "example-value",
  "GatewayState": "example-value",
  "GatewayNetworkInterfaces": "example-value",
  "GatewayType": "example-value",
  "NextUpdateAvailabilityDate": "example-value",
  "LastSoftwareUpdate": "example-value",
  "Ec2InstanceId": "example-value",
  "Ec2InstanceRegion": "example-value",
  "Tags": "example-value",
  "VPCEndpoint": "example-value",
  "CloudWatchLogGroupARN": "arn:aws:service:us-east-1:123456789012:resource/example",
  "HostEnvironment": "example-value",
  "EndpointType": "example-value",
  "SoftwareUpdatesEndDate": "example-value",
  "DeprecationDate": "example-value",
  "GatewayCapacity": "example-value",
  "SupportedGatewayCapacities": "example-value",
  "HostEnvironmentId": "example-value"
}
